pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat("C:\\SoftwareJava\\apache-maven-3.9.6\\bin\\mvn -B -DskipTests clean package")
            }
        }
        stage('Test') {
            steps {
                bat("C:\\SoftwareJava\\apache-maven-3.9.6\\bin\\mvn test")
            }
            // post {
            //     always {
            //        bat(junit 'target/surefire-reports/*.xml')
            //     }
            // }
        }
        stage('Deliver') {
            steps {
                bat('./jenkins/scripts/deliver.bat)
            }
        }
    }
}
